source 'https://github.com/cocoapods/specs.git'
source 'git@github.com:WWWarehouseMobile/BHSpecs.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'BHTencentOpenAPI_Example' do
  pod 'BHTencentOpenAPI', :path => '../'

  target 'BHTencentOpenAPI_Tests' do
    inherit! :search_paths

    
  end
end
