source 'git@github.com:WWWarehouseMobile/BHSpecs.git'

platform :ios, '9.0'

target 'BHTencentOpenAPI_Example' do
  pod 'BHTencentOpenAPI', :path => '../'

  target 'BHTencentOpenAPI_Tests' do
    inherit! :search_paths

    
  end
end
